Feature/contactus
kure-kosen/kure_kosen_map pull request #50
Opened 2018-09-25 17:41 UTC by aidmiya

# WHY

フォームのだささが想像以上にきつかったから作り直しです。

# WHAT

## やったこと

- [x] フォームを作成
- [x] フォーム周りをデザイン
- [x] *モバイル向けレイアウト作成*
- [x] 9/12分デザイン指摘の受け入れ
- [x] 背景画像の位置(PC)

## やってないこと

- [ ] ページ上部にナビゲーションバーをつける
- [ ] 背景画像の位置(モバイル)
- [ ] 間隔の微調整・ボックスモデルの整理
- [ ] 背景画像のリサイズ(縮小)

2018-09-26 16:15 UTC, aidmiya commented
PC表示はほぼこれで良いですかね？
そしてモバイルでの表示は、メニューを中心にまだ良くないところがあります。

2018-09-30 22:13 UTC, kobakazu0429 requested changes

2018-09-30 22:13 UTC, kobakazu0429 commented on src/static/assets/css/contact.css
> +    z-index: -500;
いります？

2018-09-30 22:13 UTC, kobakazu0429 commented on src/static/assets/css/contact.css
> +    z-index: -100;
これの上には何も乗ってないし、順番的にいらない気がする

2018-09-30 22:13 UTC, kobakazu0429 commented on src/static/assets/css/contact.css
> +.back-image {
名前これでいい？

2018-09-30 22:13 UTC, kobakazu0429 commented on src/static/assets/css/contact.css
> +    width: calc( 100% - 25px );
レスポンシブじゃなくない？

2018-09-30 22:13 UTC, kobakazu0429 commented on src/static/assets/css/contact.css
> +    width: calc( 100% - 5px );
ここも

2018-09-30 22:13 UTC, kobakazu0429 commented on src/static/assets/css/contact.css
> +    height: 5em;
emはあまり使いたくない

2018-09-30 22:13 UTC, kobakazu0429 commented on src/static/assets/css/pc-contact.css
> +}
改行

2018-09-30 22:13 UTC, kobakazu0429 commented on src/static/contact.html
> +  <!-- <link href="https://use.fontawesome.com/releases/v5.0.2/css/all.css" rel="stylesheet"> -->
いらないならコメントアウトじゃなくて消しましょう

2018-09-30 22:13 UTC, kobakazu0429 commented on src/static/assets/css/pc-contact.css
> +  margin-bottom: 1px solid #474747;
こんな構文あった？
margin-bottomは`px, cm, em, etc`のみだった気がするけど

2018-09-30 22:13 UTC, kobakazu0429 commented on src/static/assets/css/pc-contact.css
> +  margin-bottom: 1px solid #474747;
https://www.w3schools.com/cssref/pr_margin-bottom.asp

2018-09-30 22:15 UTC, kobakazu0429 commented
スマホ版だと上にリンクが`ul`でくるけど
https://slideout.js.org/
こんな感じで隠したほうがいいんじゃない？

2018-09-30 22:59 UTC, aidmiya commented on src/static/assets/css/pc-contact.css
> +  margin-bottom: 1px solid #474747;
すでに察しとるとは思うけど、そこはborderとの間違いだったわ、修正しておこう。

2018-09-30 23:00 UTC, aidmiya commented on src/static/contact.html
> +  <!-- <link href="https://use.fontawesome.com/releases/v5.0.2/css/all.css" rel="stylesheet"> -->
心残りが…とか言わずに消します。

2018-09-30 23:02 UTC, aidmiya commented on src/static/assets/css/contact.css
> +    height: 5em;
この場合はpxがいいのかな。
もっと良い単位があれば教えて

2018-09-30 23:04 UTC, aidmiya commented on src/static/assets/css/contact.css
> +    z-index: -100;
背景画像はフォームとかの上に来ないように-100にしたんだけどなあ
(今すぐは確認できないけど、そのままだと実際にフォームに被った覚えがある)

2018-09-30 23:05 UTC, aidmiya commented on src/static/assets/css/contact.css
> +.back-image {
適当…命名規則とか考えてないなあ…

2018-09-30 23:13 UTC, aidmiya commented on src/static/assets/css/pc-contact.css
> +}
理解

2018-10-01 12:44 UTC, kobakazu0429 commented on src/static/assets/css/contact.css
> +    height: 5em;
俺だったら`rem`かな

2018-10-01 12:47 UTC, aidmiya commented on src/static/assets/css/contact.css
> +    height: 5em;
いいですねぇ
全部remで統一も試みてもいいかもしれないな

2018-10-01 14:04 UTC, aidmiya commented on src/static/assets/css/contact.css
> +    z-index: -100;
確認してみたら、`z-index: -100;`を取り除くと`<nav>`と被るわ

2018-10-07 01:37 UTC, aidmiya commented
これで一区切り付きましたな。
いかがでしょう？

2018-10-07 01:46 UTC, aidmiya commented on src/static/contact.html
> +  <!-- <link href="https://use.fontawesome.com/releases/v5.0.2/css/all.css" rel="stylesheet"> -->
消したので閉会

2018-10-07 01:48 UTC, aidmiya commented on src/static/assets/css/contact.css
> +    height: 5em;
やっぱpxにはpxの良さもあるので全remは見送りに…

2018-10-07 01:48 UTC, aidmiya commented on src/static/assets/css/pc-contact.css
> +  margin-bottom: 1px solid #474747;
修正したので閉

2018-10-07 12:26 UTC, kobakazu0429 commented on src/static/assets/css/contact.css
> +.contact-inner ul.form-components .icon {
iconってまだあるの？

2018-10-07 12:26 UTC, kobakazu0429 commented on src/static/contact.html
> +  <header>
中身無いならタグいらないかな

2018-10-07 12:26 UTC, kobakazu0429 commented on src/static/contact.html
> +          <!-- nameなどはまだつけていません -->
次の修正でつけといて

2018-10-07 12:27 UTC, kobakazu0429 commented
全体的にLGTM !!!  :)

メニューが横だと少し見にくい気がするので最初みたいに上でいいかも
http://git.blivesta.com/drawer/top/
こんな感じで！

2018-10-07 12:28 UTC, kobakazu0429 commented
背景色も少し変えたほうが`input`と見分けがついていいかも

2018-10-07 12:28 UTC, kobakazu0429 commented
Google Formとも連携しちゃっていいよ

2018-10-07 12:41 UTC, aidmiya commented on src/static/assets/css/contact.css
> +.contact-inner ul.form-components .icon {
消し忘れだ！
見直さないと分からんもんだなあ。

2018-10-07 12:42 UTC, aidmiya commented on src/static/contact.html
> +  <header>
そのとおりであります

2018-10-07 12:44 UTC, aidmiya commented on src/static/contact.html
> +          <!-- nameなどはまだつけていません -->
いずれも同じ名前にするなら、name・idは必要だとして、classもつけるべきかな?

2018-10-07 13:02 UTC, aidmiya commented on src/static/contact.html
> +  <header>
ごみ取りしたので閉会しよう

2018-10-07 13:03 UTC, aidmiya commented on src/static/assets/css/contact.css
> +.contact-inner ul.form-components .icon {
ごみ取りしたので閉会したい

2018-10-07 13:23 UTC, aidmiya commented on src/static/contact.html
> +          <!-- nameなどはまだつけていません -->
そっか、nameはGoogle フォームのやつにすればいいんだった。
idを適当に設定すれば後は大丈夫か。

2018-10-07 13:24 UTC, aidmiya commented on src/static/assets/css/contact.css
> +    z-index: -500;
a5bde04aで消してたので閉会します

2018-10-07 13:25 UTC, aidmiya commented on src/static/assets/css/contact.css
> +.back-image {
よくわからんから.img-bgにしたよ

2018-10-07 13:28 UTC, aidmiya commented on src/static/assets/css/pc-contact.css
> +}
pc-もsp-でも修正したはずなので閉会

2018-10-07 14:18 UTC, kobakazu0429 commented on src/static/contact.html
> +          <!-- nameなどはまだつけていません -->
idも使わないんだったらいらないんじゃ無い？

2018-10-07 14:19 UTC, aidmiya commented on src/static/contact.html
> +          <!-- nameなどはまだつけていません -->
未入力確認とか(忘れてた…)で使うことがあるかもしれんぞ

2018-10-07 14:21 UTC, kobakazu0429 commented on src/static/contact.html
> +          <!-- nameなどはまだつけていません -->
html5からいらない？
http://www.htmq.com/html5/input_required.shtml

2018-10-07 14:22 UTC, aidmiya commented on src/static/contact.html
> +          <!-- nameなどはまだつけていません -->
確かにそうだったな

2018-11-10 14:19 UTC, kobakazu0429 approved these changes

2018-11-10 14:19 UTC, merged